Repository h5bp/html5please, pull requests merged in 2018-10, with the labels that each got.

#414 Update @font face
  posts/fontface.md
Labels: under-review

#425 Add ability to deselect feature
  src/js/script.js
Labels: site

#424 Remove ES5 as feature
  posts/es5.md
Labels: needs-review

#410 Add package-lock to gitignore
  .gitignore
Labels: under-review
