Repository h5bp/html5please, pull requests merged in 2019-03, with the labels that each got.

#400 Update datalist
  posts/datalist.md
Labels: needs-review

#453 update analytics to load async - faster and less code
  src/template.html
Labels: change-request

#461 Update vibration.md
  posts/vibration.md
Labels: under-review

#469 Update template.html
  src/template.html
Labels: site
